# Generated by Django 4.1.7 on 2023-04-06 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('building_name', models.CharField(max_length=100)),
                ('building_description', models.CharField(blank=True, max_length=200, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('familyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('family_name', models.CharField(max_length=50)),
                ('family_description', models.CharField(blank=True, max_length=200, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FAMILY.building')),
            ],
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('lodgeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lodge_name', models.CharField(max_length=50)),
                ('lodge_description', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.building')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('member_name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('post_weaning', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=20, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.family')),
                ('fathers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Father', to='FAMILY.member')),
                ('lodge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FAMILY.lodge')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mother', to='FAMILY.member')),
            ],
        ),
    ]
