# Generated by Django 4.1.7 on 2023-04-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fathers',
            new_name='father',
        ),
    ]
