# Generated by Django 4.1.7 on 2023-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0002_rename_fathers_member_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='generation',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
