# Generated by Django 4.1.7 on 2023-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0003_member_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='post_weaning',
            field=models.DateField(editable=False),
        ),
    ]
