# Generated by Django 4.1.7 on 2023-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0004_member_weight_alter_member_post_weaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='magnification',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pre_magnification',
            field=models.DateField(editable=False, null=True),
        ),
    ]
