# Generated by Django 4.1.7 on 2023-04-24 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0005_member_magnification_member_pre_magnification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('RegistrationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Param_Registration',
            fields=[
                ('paramRegistrationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.member')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.parameter')),
            ],
        ),
    ]
