# Generated by Django 4.1.7 on 2023-04-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0006_parameter_param_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='param_registration',
            name='date',
        ),
    ]
