# Generated by Django 4.1.7 on 2023-04-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0007_remove_param_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='weight',
        ),
    ]
