# Generated by Django 4.1.7 on 2023-04-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0008_remove_member_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='param_registration',
            name='name',
        ),
    ]
