# Generated by Django 4.1.7 on 2023-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0010_param_registration_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='RegistrationId',
            new_name='ParameterId',
        ),
        migrations.AlterField(
            model_name='param_registration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.parameter'),
        ),
    ]
