# Generated by Django 4.1.7 on 2023-04-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0012_rename_parameterid_parameter_parameterid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='param_registration',
            old_name='name',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='name',
            new_name='parameter',
        ),
    ]
