# Generated by Django 4.1.7 on 2023-05-19 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0014_rename_parameter_parameter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeRegistration',
            fields=[
                ('lodgeRegistrationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enteryDate', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('wwight', models.IntegerField(blank=True, null=True)),
                ('isFinSejour', models.BooleanField(default=False, max_length=5)),
                ('duration', models.IntegerField(editable=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.lodge')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAMILY.member')),
            ],
        ),
    ]
