# Generated by Django 4.1.7 on 2023-05-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0016_rename_lodgeregistration_lodge_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodge_registration',
            old_name='reason',
            new_name='enteryReason',
        ),
    ]
