# Generated by Django 4.1.7 on 2023-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0018_lodge_registration_leavingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge_registration',
            name='enteryReason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lodge_registration',
            name='leavingReason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
