# Generated by Django 4.1.7 on 2023-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0019_alter_lodge_registration_enteryreason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Pig',
        ),
        migrations.AlterField(
            model_name='lodge_registration',
            name='member',
            field=models.CharField(blank=True, choices=[('pig', 'Pig'), ('fowl', 'Fowl')], default='Pig', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='param_registration',
            name='member',
            field=models.CharField(blank=True, choices=[('pig', 'Pig'), ('fowl', 'Fowl')], default='Pig', max_length=20, null=True),
        ),
    ]
