# Generated by Django 4.1.7 on 2023-05-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0020_rename_member_pig_alter_lodge_registration_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='param_registration',
            name='pig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pig', to='FAMILY.param_registration'),
        ),
    ]
