# Generated by Django 4.1.7 on 2023-05-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0026_fowl_lodge_registration_param_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='param_registration',
            name='member',
        ),
        migrations.RemoveField(
            model_name='param_registration',
            name='member_type',
        ),
    ]
