# Generated by Django 4.1.7 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0027_remove_param_registration_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='param_registration',
            name='member_choice',
            field=models.CharField(blank=True, choices=[('pig', 'Pig'), ('fowl', 'Fowl')], default='Pig', max_length=20, null=True),
        ),
    ]
