# Generated by Django 4.1.7 on 2023-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0028_param_registration_member_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='param_registration',
            name='member',
            field=models.CharField(blank=True, choices=[], default='Pig', max_length=20, null=True),
        ),
    ]
