# Generated by Django 4.1.7 on 2023-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAMILY', '0030_alter_param_registration_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param_registration',
            name='member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
