# Generated by Django 4.1.6 on 2023-02-11 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('niu', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('bankaccount', models.CharField(blank=True, max_length=255, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('deptnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, max_length=10, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('celibat', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf ', 'Veuf(ve)'), ('concubin', 'Concubinage')], default='celibat', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('hiringdate', models.DateField(blank=True, max_length=10, null=True)),
                ('seniority', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsappnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('facebooklink', models.CharField(blank=True, max_length=255, null=True)),
                ('resourcecontact', models.CharField(blank=True, max_length=255, null=True)),
                ('resourcename', models.CharField(blank=True, max_length=255, null=True)),
                ('isChiefOfDepartment', models.BooleanField(default=False, max_length=5)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.department')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('documentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numCni', models.CharField(blank=True, max_length=255, null=True)),
                ('cniupload', models.FileField(null=True, upload_to='')),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('diplomaupload', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('marriagecertificate', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contract_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofcreation', models.DateField(blank=True, max_length=255, null=True)),
                ('duration', models.DateField(blank=True, max_length=255, null=True)),
                ('formofcontract', models.CharField(blank=True, max_length=255, null=True)),
                ('contractupload', models.FileField(blank=True, null=True, upload_to='ContractFile/contract.pdf')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('agents', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.agent')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.employee')),
            ],
        ),
    ]
