# Generated by Django 4.1.7 on 2023-03-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='external',
            name='agent',
            field=models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('client', 'Client')], default='client', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='external',
            name='Supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.supplier'),
        ),
        migrations.AlterField(
            model_name='external',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.client'),
        ),
    ]
