# Generated by Django 4.1.7 on 2023-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_external_agent_alter_external_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external',
            name='agent',
            field=models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('client', 'Client')], max_length=255, null=True),
        ),
    ]
